{config, pkgs, lib, ...}:

{
    home.username = "lunear";
    home.homeDirectory = "/home/lunear";
    home.stateVersion = "26.05";


    # Programs
    programs.bash = {
        enable = true;
        shellAliases = {
            nrs = "sudo nixos-rebuild --flake /etc/nixos#lunear-nixos switch";
            btw = "echo i use nix btw";
        };
    };
    programs.waybar = {
        enable = true;
        systemd.enable = true;
    };
    programs.git.enable = true;
    programs.kitty = {
        enable = true;
        # Pull the wallpaper-derived palette in. Regenerated by scripts/theme.sh;
        # open windows also recolor live via wallust's escape sequences.
        extraConfig = ''
            include /home/lunear/.cache/wal/colors-kitty.conf
        '';
    };
    programs.rofi = {
        enable = true;
        # Layout lives in the repo; colors come from the wallpaper via wallust.
        theme = "/home/lunear/.config/rofi/theme.rasi";
    };
    programs.fastfetch.enable = true;
    programs.vscode.enable = true;

    # wallust — generates the colorscheme from the wallpaper (see wallust/).
    home.packages = [ pkgs.wallust ];

    # Services
    services.swaync.enable = true;
    services.cliphist.enable = true;
    services.playerctld.enable = true;

    # Session target — the home-manager user services above (waybar, swaync,
    # cliphist, playerctld) are bound to graphical-session.target, which has
    # RefuseManualStart=yes and only activates when a compositor session target
    # binds it in. Our minimal Lua Hyprland config isn't launched via uwsm, so
    # we define and start that target ourselves (see hypr/hyprland.lua autostart).
    systemd.user.targets.hyprland-session = {
        Unit = {
            Description = "Hyprland compositor session";
            Documentation = [ "man:systemd.special(7)" ];
            BindsTo = [ "graphical-session.target" ];
            Before = [ "graphical-session.target" ];
            Wants = [ "graphical-session-pre.target" ];
            After = [ "graphical-session-pre.target" ];
        };
    };

    # Dotfiles — copied into the Nix store and symlinked declaratively.
    # Sources live in this flake (git-tracked), so edits need a rebuild (`nrs`)
    # to take effect. Runtime theming still works: wallust writes its generated
    # palette to ~/.cache/wal/, which these configs @import/include.
    xdg.configFile = {
        "hypr/hyprland.lua".source = ./hypr/hyprland.lua;
        "waybar/config.jsonc".source = ./waybar/config.jsonc;
        "waybar/style.css".source = ./waybar/style.css;

        # Pywal-style theming via wallust: wallpaper -> palette -> every app.
        "wallust/wallust.toml".source = ./wallust/wallust.toml;
        "wallust/templates".source = ./wallust/templates;
        "rofi/theme.rasi".source = ./rofi/theme.rasi;
        "swaync/style.css".source = ./swaync/style.css;

        # Scripts are exec'd directly (see hypr/hyprland.lua), so keep +x.
        "hypr/scripts/theme.sh" = {
            source = ./scripts/theme.sh;
            executable = true;
        };
        "hypr/scripts/wallpaper-picker.sh" = {
            source = ./scripts/wallpaper-picker.sh;
            executable = true;
        };
    };
}
