{config, pkgs, lib, ...}:

{
    home.username = "lunear";
    home.homeDirectory = "/home/lunear";
    home.stateVersion = "26.05";


    # Programs
    programs.bash = {
        enable = true;
        shellAliases = {
            nrs = "sudo nixos-rebuild --flake /etc/nixos#lunear-nixos switch";
            btw = "echo i use nix btw";
        };
    };
    programs.waybar = {
        enable = true;
        systemd.enable = true;
    };
    programs.git.enable = true;
    programs.kitty = {
        enable = true;
        # Pull the wallpaper-derived palette in. Regenerated by scripts/theme.sh;
        # open windows also recolor live via wallust's escape sequences.
        extraConfig = ''
            include /home/lunear/.cache/wal/colors-kitty.conf
        '';
    };
    programs.rofi = {
        enable = true;
        # Layout lives in the repo; colors come from the wallpaper via wallust.
        theme = "/home/lunear/.config/rofi/theme.rasi";
    };
    programs.fastfetch.enable = true;
    programs.vscode.enable = true;

    # wallust — generates the colorscheme from the wallpaper (see wallust/).
    home.packages = [ pkgs.wallust ];

    # Services
    services.swaync.enable = true;
    services.cliphist.enable = true;
    services.playerctld.enable = true;

    # Session target — the home-manager user services above (waybar, swaync,
    # cliphist, playerctld) are bound to graphical-session.target, which has
    # RefuseManualStart=yes and only activates when a compositor session target
    # binds it in. Our minimal Lua Hyprland config isn't launched via uwsm, so
    # we define and start that target ourselves (see hypr/hyprland.lua autostart).
    systemd.user.targets.hyprland-session = {
        Unit = {
            Description = "Hyprland compositor session";
            Documentation = [ "man:systemd.special(7)" ];
            BindsTo = [ "graphical-session.target" ];
            Before = [ "graphical-session.target" ];
            Wants = [ "graphical-session-pre.target" ];
            After = [ "graphical-session-pre.target" ];
        };
    };

    # Dotfiles — symlinked live to the repo so edits apply without a rebuild.
    # Requires the flake to be cloned at /etc/nixos (the standard location).
    
    xdg.configFile."hypr/hyprland.lua".source =
        config.lib.file.mkOutOfStoreSymlink "/etc/nixos/hypr/hyprland.lua";
    xdg.configFile."waybar/config.jsonc".source =
        config.lib.file.mkOutOfStoreSymlink "/etc/nixos/waybar/config.jsonc";
    xdg.configFile."waybar/style.css".source =
        config.lib.file.mkOutOfStoreSymlink "/etc/nixos/waybar/style.css";

    # Pywal-style theming via wallust: wallpaper -> palette -> every app.
    xdg.configFile."wallust/wallust.toml".source =
        config.lib.file.mkOutOfStoreSymlink "/etc/nixos/wallust/wallust.toml";
    xdg.configFile."wallust/templates".source =
        config.lib.file.mkOutOfStoreSymlink "/etc/nixos/wallust/templates";
    xdg.configFile."rofi/theme.rasi".source =
        config.lib.file.mkOutOfStoreSymlink "/etc/nixos/rofi/theme.rasi";
    xdg.configFile."swaync/style.css".source =
        config.lib.file.mkOutOfStoreSymlink "/etc/nixos/swaync/style.css";
    xdg.configFile."hypr/scripts/theme.sh".source =
        config.lib.file.mkOutOfStoreSymlink "/etc/nixos/scripts/theme.sh";
    xdg.configFile."hypr/scripts/wallpaper-picker.sh".source =
        config.lib.file.mkOutOfStoreSymlink "/etc/nixos/scripts/wallpaper-picker.sh";
}
