-- Auto-generated by wallust. Outputs to ~/.cache/wal/colors-hyprland.lua
-- Loaded by ~/.config/hypr/hyprland.lua via dofile() for live color theming.
-- Colors are emitted in Hyprland's rgba(RRGGBBAA) string format, blended 50/50
-- toward their Everforest Dark Hard anchors to match the static Stylix theme.
return {
    wallpaper  = "{{wallpaper}}",
    foreground = "rgba({{foreground | blend("d3c6aa") | strip}}ff)",
    background = "rgba({{background | blend("272e33") | strip}}ff)",
    color0  = "rgba({{color0  | blend("272e33") | strip}}ff)",
    color1  = "rgba({{color1  | blend("e67e80") | strip}}ff)",
    color2  = "rgba({{color2  | blend("a7c080") | strip}}ff)",
    color3  = "rgba({{color3  | blend("dbbc7f") | strip}}ff)",
    color4  = "rgba({{color4  | blend("7fbbb3") | strip}}ff)",
    color5  = "rgba({{color5  | blend("d699b6") | strip}}ff)",
    color6  = "rgba({{color6  | blend("83c092") | strip}}ff)",
    color7  = "rgba({{color7  | blend("d3c6aa") | strip}}ff)",
    color8  = "rgba({{color8  | blend("859289") | strip}}ff)",
    color9  = "rgba({{color9  | blend("e67e80") | strip}}ff)",
    color10 = "rgba({{color10 | blend("a7c080") | strip}}ff)",
    color11 = "rgba({{color11 | blend("dbbc7f") | strip}}ff)",
    color12 = "rgba({{color12 | blend("7fbbb3") | strip}}ff)",
    color13 = "rgba({{color13 | blend("d699b6") | strip}}ff)",
    color14 = "rgba({{color14 | blend("83c092") | strip}}ff)",
    color15 = "rgba({{color15 | blend("fffbef") | strip}}ff)",
}
